### ISSUE TITLE
Mihai Pop (maximisu90) review

### ISSUE THREAD

**Issue by maximisu90** [teokem/project-work-2021-LeaMikoV#2]
Documentation:

    title and abstract of the project (max 300 words) 

**The Abstract is not clearly visible eve though the same function  as the abstract is accomplished by the introduction and General information chapter**

    includes instructions on how to run the notebook
**Very good description for each cell **

    includes the required packages in an environment.yml file 

**Yes**

    includes a brief explanation of the reason each package/library was used

**Not all packages are described **

    includes rich documentation using Markdown (equations, tables, links, images or videos)

**Yes**

    is reproducible, i.e., someone else should be able to redo the steps

**Yes**

Input/Output:

    uses pandas to read large data sets or numpy to load data from text files 

**Not Large datasets but defenitly datasets**

    uses pandas to save to disk the processed or generated data

**yes**

Scientific computing/data processing:
    performs numerical operations (numpy, scipy, pandas) or manipulates, groups, and aggregates a data set (pandas)

**Yes**

Data visualization:

    includes at least one composite plot (inset or multiple panels)

**Yes**

    produces publication ready quality figures (see here for an editorial guide on Graphical Excellence):
        the figures are 89 mm wide (single column) or 183 mm wide (double column)
        the axes are labeled
        the font sizes are sufficiently large
        the figures are saved as rasterized images (300 dpi) or vector art

**Yes**

**I would say this is a very good project which meets all the requirements**

**Comment by LeaMikoV** [comment]
Thank you for the feedback! I added the abstract to the notebook as well and double-checked that all packages are described. I added that I am loading the scikit-learn package since I assume you were referring to the missing description of that package.
