### ISSUE TITLE
Review Simon

### ISSUE THREAD

**Issue by si8881wo** [teokem/project-work-2021-LeaMikoV#3]
(I skip the subpoints)
- [x] Documentation: all criteria fulfilled in the readme, very nice introduction and description of the project, (note on #2 about the missing package description: I assume that concerns when you call `from sklearn.preprocessing import PolynomialFeatures ... ` in cell 17, maybe you could add a comment about that that is loading scikit-learn)
- [x] In/Output: I'm personally not a huge fan of excel files (can't expect everyone to have access to excel) and think .csv or another text based file format make sense. After all you are doing all the fancy plotting in python anyways so no need to use a proprietary format. Just my personal preference though.
- [x] Scientific computing/data processing: nicely done and commented what happens in the cells that perform these operations
- [x] Data visualization: plenty of super nice plots, I especially like the interactive ones where you can play around with the parameters and have a lot of options to choose from (dropdown + slider) the only downside of those is the humongous code cell before them that kind of breaks the flow when reading. I don't really have a solution for that though, nor do I think there is one other than hiding the codecell. I also think you made a very good choice in what plots to actually save to disk and which ones to have interactive.
- [x] Version control, sharing, and archiving: there and working

Overall feedback: I really think this is a very complete project that has a lot of nice figures and makes good use of a given data set. Maybe you could have chose to pull the data directly from the linked websites, I assume the files have some permalink, but the way you do it you can of course be sure everything is there at all times. The only think I'm not super happy with is the huge code cells before the interactive plot but as I said, I don't have a solution for that. I also don't think it really takes anything away from this great notebook!

**Comment by LeaMikoV** [comment]
Thank you for the feedback! I made the changes you suggested, i.e. I added that I am loading the svikit-learn package and save the data as .csv file.
As you assumed, I prefer to load the data from the files and not from a link in order to be sure that the notebook can be run even if the links won't exist any longer. 
I also do not have a better idea how to avoid cells with a lot of code to produce interactive plots, except of maybe having another file with routines for these plots which can be called.
